language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3  

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1

    - php: 7.0
      env: COVERAGE=1

    - php: 7.0
      env: CAKEPHP_VERSION="3.4.*"

    - php: 7.0
      env: CAKEPHP_VERSION="3.5.*"

    - php: 7.0
      env: CAKEPHP_VERSION="3.6.*"

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - if [[ ! -z "$CAKEPHP_VERSION" ]]; then composer require --update-with-dependencies cakephp/cakephp:${CAKEPHP_VERSION}; fi
  - if [[ ! -z "$PHPUNIT_VERSION" ]]; then composer require --update-with-dependencies phpunit/phpunit:${PHPUNIT_VERSION}; fi
  
script:
  - if [[ $PHPCS != '1' && $COVERAGE != '1' ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs --standard=phpcs.xml.dist; fi
  - if [[ $COVERAGE = 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  
after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
